<?php

/**
 * @file
 * Contains smmg_invoice.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function smmg_invoice_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the smmg_invoice module.
    case 'help.page.smmg_invoice':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Invoicees Module for Small Messages') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function smmg_invoice_theme() {
  return [
    'smmg_invoice' => [
      'render element' => 'children',
    ],
  ];
}
